// <copyright file="StatIds.cs" company="Athavar">
// Copyright (c) Athavar. All rights reserved.
// Licensed under the GPL-3.0 license. See LICENSE file in the project root for full license information.
// </copyright>

namespace Athavar.FFXIV.Plugin.Models.Constants;

public enum StatIds : byte
{
    None = 0,
    Strength = 1,
    Dexterity = 2,
    Vitality = 3,
    Intelligence = 4,
    Mind = 5,
    Piety = 6,
    HP = 7,
    MP = 8,
    TP = 9,
    GP = 10,
    CP = 11,
    PhysicalDamage = 12,
    MagicalDamage = 13,
    Delay = 14,
    AdditionalEffect = 15,
    AttackSpeed = 16,
    BlockRate = 17,
    BlockStrength = 18,
    Tenacity = 19,
    AttackPower = 20,
    Defense = 21,
    DirectHitRate = 22,
    Evasion = 23,
    MagicDefense = 24,
    CriticalHitPower = 25,
    CriticalHitResilience = 26,
    CriticalHit = 27,
    CriticalHitEvasion = 28,
    SlashingResistance = 29,
    PiercingResistance = 30,
    BluntResistance = 31,
    ProjectileResistance = 32,
    AttackMagicPotency = 33,
    HealingMagicPotency = 34,
    EnhancementMagicPotency = 35,
    EnfeeblingMagicPotency = 36,
    FireResistance = 37,
    IceResistance = 38,
    WindResistance = 39,
    EarthResistance = 40,
    LightningResistance = 41,
    WaterResistance = 42,
    MagicResistance = 43,
    Determination = 44,
    SkillSpeed = 45,
    SpellSpeed = 46,
    Haste = 47,
    Morale = 48,
    Enmity = 49,
    EnmityReduction = 50,
    CarefulDesynthesis = 51,
    EXPBonus = 52,
    Regen = 53,
    Refresh = 54,
    MovementSpeed = 55,
    Spikes = 56,
    SlowResistance = 57,
    PetrificationResistance = 58,
    ParalysisResistance = 59,
    SilenceResistance = 60,
    BlindResistance = 61,
    PoisonResistance = 62,
    StunResistance = 63,
    SleepResistance = 64,
    BindResistance = 65,
    HeavyResistance = 66,
    DoomResistance = 67,
    ReducedDurabilityLoss = 68,
    IncreasedSpiritbondGain = 69,
    Craftsmanship = 70,
    Control = 71,
    Gathering = 72,
    Perception = 73,
    Unknown73 = 74,
}