name: Build

# Put your personal access token in a repository secret named PAT for cross-repository access

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  PUBLIC_NAME: Athavar's Tools
  SOLUTION_NAME: Athavar.FFXIV.Plugin
  INTERNAL_NAME: Athavar.FFXIV.Plugin
  RELEASE_DIR: Athavar.FFXIV.Plugin\bin\Release\Athavar.FFXIV.Plugin
  PERSONAL_PLUGIN_REPO: Athavar/Athavar.FFXIV.DalaRepo

jobs:
  build:
    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.GIT_SECRET }}
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1
      - name: Download Dalamud
        run: |
          Invoke-WebRequest -Uri https://goatcorp.github.io/dalamud-distrib/latest.zip -OutFile latest.zip
          Expand-Archive -Force latest.zip "$env:AppData\XIVLauncher\addon\Hooks\dev\"   
      - name: Build
        run: |
          dotnet restore -r win ${{ env.SOLUTION_NAME }} -v n
          dotnet build --configuration Release -v n
        env:
          DOTNET_CLI_TELEMETRY_OPTOUT: true
      - uses: actions/upload-artifact@v3
        with:
          name: PluginRepoZip
          path: ${{ env.RELEASE_DIR }}
          if-no-files-found: error

  deploy:
    needs: build
    if: "contains(toJSON(github.event.commits.*.message), '[PUSH]')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          repository: ${{ env.PERSONAL_PLUGIN_REPO }}
          token: ${{ secrets.PAT }}
      - uses: actions/download-artifact@v3
        with:
          name: PluginRepoZip
          path: plugins/${{ env.INTERNAL_NAME }}
      - uses: EndBug/add-and-commit@v9
        with:
          add: --all
          author_name: GitHub Action
          author_email: action@github.com
          message: Update ${{ env.INTERNAL_NAME }}