name: Build

# Add a concurrency group in-case a tag is created, deleted, and then recreated while a release is in progress.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  pull_request:

env:
  PUBLIC_NAME: "Athavar's Tools"
  SOLUTION_NAME: 'Athavar.FFXIV.Plugin'
  INTERNAL_NAME: 'Athavar.FFXIV.Plugin'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    env:
      IsCI: true
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GIT_SECRET }}
          submodules: recursive

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      - name: Download Dalamud
        run: |
          wget https://goatcorp.github.io/dalamud-distrib/latest.zip -O /tmp/dalamud.zip
          unzip /tmp/dalamud.zip -d /tmp/dalamud

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build
        run: |
          dotnet build --configuration Release -v n /p:DalamudLibPath="/tmp/dalamud" -o ./bin/Release ${{ env.INTERNAL_NAME }}
        env:
          DOTNET_CLI_TELEMETRY_OPTOUT: true

      - uses: actions/upload-artifact@v3
        with:
          name: PluginRepoZip
          path: ./bin/Release/${{ env.INTERNAL_NAME }}
          if-no-files-found: error

  deploy:
    needs: build
    if: "contains(toJSON(github.event.commits.*.message), '[PUSH]')"
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: false
          repository: ${{ env.PERSONAL_PLUGIN_REPO }}
          token: ${{ secrets.PAT }}
      - uses: actions/download-artifact@v3
        with:
          name: PluginRepoZip
          path: plugins/${{ env.INTERNAL_NAME }}
      - uses: EndBug/add-and-commit@v9
        with:
          add: --all
          author_name: GitHub Action
          author_email: action@github.com
          message: Update ${{ env.INTERNAL_NAME }}